version: "3.5"
services:
  web-server:
    image: "lbbxsxlz/python:3.5"
    build: .
    command: python app.py
    ports:
      - target: 5000
        published: 5000
    networks:
      - counter-net
    volumes:
      - type: volume
        source: counter-vol
        target: /counter-code
  redis:
    image: "redis"
    networks:
      counter-net:

networks:
  counter-net:

volumes:
  counter-vol:

